-- Phase 8 — School Management schema additions
USE `learning_platform`;

CREATE TABLE IF NOT EXISTS `school_classes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `school_id` BIGINT UNSIGNED NOT NULL,
  `campus_id` BIGINT UNSIGNED NULL,
  `academic_year_id` BIGINT UNSIGNED NOT NULL,
  `grade_id` BIGINT UNSIGNED NOT NULL,
  `code` VARCHAR(32) NOT NULL,
  `name_en` VARCHAR(100) NOT NULL,
  `name_ar` VARCHAR(100) NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'active',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `school_classes_year_grade_code_unique` (`academic_year_id`, `grade_id`, `code`),
  KEY `school_classes_tenant_school_index` (`tenant_id`, `school_id`),
  KEY `school_classes_campus_id_index` (`campus_id`),
  CONSTRAINT `school_classes_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`),
  CONSTRAINT `school_classes_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`),
  CONSTRAINT `school_classes_campus_id_foreign` FOREIGN KEY (`campus_id`) REFERENCES `campuses` (`id`),
  CONSTRAINT `school_classes_academic_year_id_foreign` FOREIGN KEY (`academic_year_id`) REFERENCES `academic_years` (`id`),
  CONSTRAINT `school_classes_grade_id_foreign` FOREIGN KEY (`grade_id`) REFERENCES `grades` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Link existing class_sections (sections) to optional parent class
ALTER TABLE `class_sections`
  ADD COLUMN `school_class_id` BIGINT UNSIGNED NULL AFTER `grade_id`,
  ADD KEY `class_sections_school_class_id_index` (`school_class_id`),
  ADD CONSTRAINT `class_sections_school_class_id_foreign`
    FOREIGN KEY (`school_class_id`) REFERENCES `school_classes` (`id`) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS `calendar_events` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `school_id` BIGINT UNSIGNED NOT NULL,
  `campus_id` BIGINT UNSIGNED NULL,
  `academic_year_id` BIGINT UNSIGNED NULL,
  `term_id` BIGINT UNSIGNED NULL,
  `title_en` VARCHAR(255) NOT NULL,
  `title_ar` VARCHAR(255) NOT NULL,
  `event_type` VARCHAR(32) NOT NULL DEFAULT 'general',
  `starts_on` DATE NOT NULL,
  `ends_on` DATE NOT NULL,
  `is_all_day` TINYINT(1) NOT NULL DEFAULT 1,
  `description_en` TEXT NULL,
  `description_ar` TEXT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'published',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  KEY `calendar_events_school_dates_index` (`school_id`, `starts_on`, `ends_on`),
  KEY `calendar_events_tenant_school_index` (`tenant_id`, `school_id`),
  KEY `calendar_events_type_index` (`event_type`),
  CONSTRAINT `calendar_events_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`),
  CONSTRAINT `calendar_events_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`),
  CONSTRAINT `calendar_events_campus_id_foreign` FOREIGN KEY (`campus_id`) REFERENCES `campuses` (`id`),
  CONSTRAINT `calendar_events_academic_year_id_foreign` FOREIGN KEY (`academic_year_id`) REFERENCES `academic_years` (`id`),
  CONSTRAINT `calendar_events_term_id_foreign` FOREIGN KEY (`term_id`) REFERENCES `terms` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `timetables` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `school_id` BIGINT UNSIGNED NOT NULL,
  `campus_id` BIGINT UNSIGNED NULL,
  `academic_year_id` BIGINT UNSIGNED NOT NULL,
  `term_id` BIGINT UNSIGNED NULL,
  `class_section_id` BIGINT UNSIGNED NOT NULL,
  `name_en` VARCHAR(191) NOT NULL,
  `name_ar` VARCHAR(191) NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'draft',
  `effective_from` DATE NULL,
  `effective_to` DATE NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  KEY `timetables_tenant_school_index` (`tenant_id`, `school_id`),
  KEY `timetables_section_status_index` (`class_section_id`, `status`),
  CONSTRAINT `timetables_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`),
  CONSTRAINT `timetables_school_id_foreign` FOREIGN KEY (`school_id`) REFERENCES `schools` (`id`),
  CONSTRAINT `timetables_campus_id_foreign` FOREIGN KEY (`campus_id`) REFERENCES `campuses` (`id`),
  CONSTRAINT `timetables_academic_year_id_foreign` FOREIGN KEY (`academic_year_id`) REFERENCES `academic_years` (`id`),
  CONSTRAINT `timetables_term_id_foreign` FOREIGN KEY (`term_id`) REFERENCES `terms` (`id`),
  CONSTRAINT `timetables_class_section_id_foreign` FOREIGN KEY (`class_section_id`) REFERENCES `class_sections` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `timetable_slots` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tenant_id` BIGINT UNSIGNED NOT NULL,
  `timetable_id` BIGINT UNSIGNED NOT NULL,
  `weekday` TINYINT UNSIGNED NOT NULL COMMENT '0=Sunday .. 6=Saturday',
  `period_no` INT UNSIGNED NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `subject_id` BIGINT UNSIGNED NOT NULL,
  `teacher_user_id` BIGINT UNSIGNED NULL,
  `room` VARCHAR(64) NULL,
  `notes` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` DATETIME NULL,
  `created_by` BIGINT UNSIGNED NULL,
  `updated_by` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  KEY `timetable_slots_timetable_weekday_index` (`timetable_id`, `weekday`, `start_time`),
  KEY `timetable_slots_teacher_index` (`teacher_user_id`),
  KEY `timetable_slots_subject_id_index` (`subject_id`),
  CONSTRAINT `timetable_slots_tenant_id_foreign` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`),
  CONSTRAINT `timetable_slots_timetable_id_foreign` FOREIGN KEY (`timetable_id`) REFERENCES `timetables` (`id`) ON DELETE CASCADE,
  CONSTRAINT `timetable_slots_subject_id_foreign` FOREIGN KEY (`subject_id`) REFERENCES `subjects` (`id`),
  CONSTRAINT `timetable_slots_teacher_user_id_foreign` FOREIGN KEY (`teacher_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
